### ISSUE TITLE
Compile with node12 error

### ISSUE THREAD

**Issue by ruslan-gennadievich** [Saevon/node-diskfree#3]
/home/ruslan/snap/code/common/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/disk-gyp.cpp:196:64: error: no matching function for call to ‘v8::Number::NumberValue()’
         double error = args[0]->ToNumber(isolate)->NumberValue();

**Comment by Saevon** [comment]
Should be updated for Node 2/13 with the latest release (1.2.0)
